### ISSUE TITLE
installation introduces React.PropTypes validation warning

### ISSUE THREAD

**Issue by ryanrogalski** [marnusw/react-css-transition-replace#27]
First of all, awesome plugin, thanks for taking the time to build it 🙏🏻

When I add this package to my app, I see a bunch of warnings about PropTypes validations:

![screen shot 2016-09-28 at 10 30 38 am](https://cloud.githubusercontent.com/assets/1111881/18925001/07721bd2-8567-11e6-80e5-4097a8969e2b.png)

https://facebook.github.io/react/warnings/dont-call-proptypes.html

Will this be fixed in future versions?

**Comment by marnusw** [comment]
Yes, I guess this changed in the very latest version of React. I haven't
seen it yet. Just give me a few days though please. Or if you want to make
a PR that would be great.

**Comment by ryanrogalski** [comment]
No problem man, I encountered this on a client project and it's not critical so I will just wait for an update as I don't have the bandwidth to fix it right now.

Thanks again.

**Comment by marnusw** [comment]
I've looked into this but I'm unable to reproduce the warnings you saw and if I look at the image you attached I'm thinking the problem might have been in the version of `react-router` that you are running?

Since [Declaring PropTypes is still fine](https://facebook.github.io/react/warnings/dont-call-proptypes.html#declaring-proptypes-is-still-fine) and the code in this lib still matches that in `ReactCSSTransitionGroupChild@15.3.2` I think we're OK here. [This conversation](https://github.com/facebook/react/pull/7132#issuecomment-229852126) further suggests it might have been a router issue.

I'm not sure why this message would have shown up only after you included `react-css-transition-replace` though. Would you mind giving it another go with the latest v2/v3 or `react-router`?

**Comment by ryanrogalski** [comment]
@marnusw it is most likely an issue with another dependency, this was on a client project that had a lot of other developers working on it
