### ISSUE TITLE
Incorrect node when state changes faster than transition.

### ISSUE THREAD

**Issue by alexanderzubarev** [marnusw/react-css-transition-replace#29]
You can see it on http://marnusw.github.io/react-css-transition-replace/ in last section (Add/Remove Content).

If you click the "Click to add content/Click to remove content" button quickly enough, image state will be incorrect (no image with "Click to remove content" button): 
![2016-10-19 15 35 22](https://cloud.githubusercontent.com/assets/14856465/19513446/1b1e2cfc-961a-11e6-96f3-f0bee041a4aa.png)

**Comment by marnusw** [comment]
Thanks for the note @alexanderzubarev. It looks like it happens when you click the link at a specific point during the removal. i.e. while the previous content is being removed, the new content isn't added. I should be looking at this lib again soon and will then investigate.

**Comment by cooperka** [comment]
Any updates @marnusw? I think there's a dupe here too: https://github.com/marnusw/react-css-transition-replace/issues/38

This would be great to have, I think your library is really useful but there's no way I can use it while it has this bug. I'm using it for hover events, and it triggers this bug nearly every time because the hover state can change so rapidly.

**Comment by marnusw** [comment]
I have merged #34 which might help with this issue, although it seems that didn't quite solve it. I've been working on pretty much a complete rewrite of the library on the `next` branch. I think that might solve the issue you're having. It's probably not quite ready for a release and I haven't had time to work on it in a while, but if you find it a step in the right direction feel free to create PRs against it. I'll put in some more time when I can.
