### ISSUE TITLE
nextChild span

### ISSUE THREAD

**Issue by mvirbicianskas** [marnusw/react-css-transition-replace#36]
i can see i'm able to set any component i want, but it seems there's additional wrapper which is by default - span, this is not good in cases where you have div > span > div; or maybe there's a way to set it like componentChild?

**Comment by marnusw** [comment]
The extra `span` is used to absolutely position the next child on top of the current one without affecting the styles of the child itself. Have you found a solution to your problem since opening this issue? If not perhaps we could consider a property for controlling this wrapper, but a span was chosen because it is usually pretty transparent unless styled directly.

**Comment by mvirbicianskas** [comment]
i'm still using the original implementation, span that is, but i think better solution would be to just use div by default with preset style properties 'inherit' if need be. Also found another problem, where you animate an element's height  and the parent div has no width set, on first render during the animation you can see that content is shrunk (meaning it's width is as wide as content, not parent's), i think a good idea would be to set width to 100% which would be always the width of it's parent, but maybe this only in my case, but this problem occurred twice in the project i'm working on, either way, simplest solution i think would be to provide ability for controlling wrapping div and child span/div styles

**Comment by marnusw** [comment]
Closed by #40

**Comment by mvirbicianskas** [comment]
@marnusw thanks! will test this this week and let you know if anything comes up :)
