### ISSUE TITLE
Option to delay height change until after leave animation completes

### ISSUE THREAD

**Issue by chrisrichard** [marnusw/react-css-transition-replace#43]
For a fade-out-then-fade-in transition within a scrollable container it's preferable to keep the height as is until after the fade-out (leave) transition completes. Can this be an option in the props? 

Give me a little direction and I can submit a PR.

**Comment by marnusw** [comment]
Since this issue is ancient by now I would imagine this isn't directly relevant anymore, but an easy solution that just occurred to me is simply to delay the height animation in the CSS. See the added [`fade-wait-delay` animation](https://github.com/marnusw/react-css-transition-replace/blob/222057dd4ec5083aa8ea1d4a512f945108cc1bf3/demo/assets/transitions.css#L51) as an example. 

By specifying a delay on the height transition, such as the `.4s` below, to match the duration of the `leave` transition I believe you can achieve what you were after.

```CSS
.fade-wait-height {
  transition: height .6s ease-in-out .4s;
}
```
