### ISSUE TITLE
height is not calculating correctly if children has margin

### ISSUE THREAD

**Issue by nomoreboredom** [marnusw/react-css-transition-replace#47]
Not sure if I am missing something, but I am using this package with react-router and pass this:

`{React.cloneElement(this.props.children, {key: location.pathname})}` to my ReactCSSTransitionReplace element.

In relation, if the root elements of the children routes has margin-top style prop, the transition height is not calculated correctly.

Instead have to use padding-top.

Thanks for great package!

**Comment by AlbinHolmlund** [comment]
I had a similar problem recently;
Try wrapping everything inside your ```<ReactCSSTransitionReplace>``` with a container set to ```overflow: hidden```. Like this:
```jsx
<ReactCSSTransitionReplace>
    <div style={{overflow: 'hidden'}}>
        { stuff }
    </div>
</ReactCSSTransitionReplace>
```

**Comment by marnusw** [comment]
@nomoreboredom the library uses the [`offsetHeight`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight) of the leaving/entering children to find values for the height animation which does not include the margin of the element. If you wish to add a top margin to all children  the best way would be to add the `className` or `style` to the `RCTReplace` component itself rather than the children. If only some children require margin/padding then using `padding-top` would be the simplest way to realize this.

@AlbinHolmlund the container uses overflow hidden to hide overflowing content while animating the transition so applying that again to the child may cause some unexpected results. You could try applying the style to the RCTReplace container itself or wrap the container in the `div` in your example instead. Alternatively you can try setting the `overflowHidden` prop of the container to `false`: 

```javascript
<ReactCSSTransitionReplace overflowHidden={false} {...}>
  /* ... */
</ReactCSSTransitionReplace>
```

**Comment by nomoreboredom** [comment]
@marnusw Thanks a lot for detailed explanation, I am closing the issue now.
