### ISSUE TITLE
Support for more than one child?

### ISSUE THREAD

**Issue by fixpunkt** [marnusw/react-css-transition-replace#5]
I'm currently trying to figure out how to properly animate a list of Bootstrap breadcrumbs. Using CSSTransitionGroup from React results in the breadcrumbs list to expand to accommodate both the entering and leaving breadcrumbs and then contracting again when the leaving component is removed from the DOM.

I was hoping to use this component to fix my problem, but unfortunately, it is restricted to a single child. What would be required to also support multiple children? Would you be interested in merging such a feature?

**Comment by marnusw** [comment]
I'm not sure if I understand what you want to do correctly, but this would be my approach to animating a list of breadcrums that fade out/in when they change:

```javascript
<ReactCSSTransitionReplace transitionName="cross-fade" /*...timeouts...*/>
  <ol class="breadcrumb" key={url}>
    {paths.map(/* Render your <li>'s here */)}
  </ol>
</ReactCSSTransitionReplace>
```

Here `ReactCSSTransitionReplace` still only has a single `child`, even though it has many grandchildren which is fine. Since the url is used as the `key` the breadcrums will update whenever the url changes (might need some tweaking or another strategy here). Then you just use whatever logic you're currently using to map out the *current* breadcrums in the list. 

You should see your old breadcrums fade out and replaced by the new *current* breadcrums as long as the `ReactCSSTransitionReplace` stays mounted when the page content is updated.

**Comment by fixpunkt** [comment]
Wow. That approach didn't even occur to me. But it should work just fine for my case. Thanks for clarifying!
