### ISSUE TITLE
3.0.0 changelog/breaking changes?

### ISSUE THREAD

**Issue by FezVrasta** [marnusw/react-css-transition-replace#51]
May you provide a changelog/breaking changes list from 2.0 to 3.0? It's quite difficult to spot the differences otherwise.

Thanks.

**Comment by marnusw** [comment]
I will look at improving the style/layout of the changelog to improve this. The only breaking API change is minor and described in the [upgrade guide](https://github.com/marnusw/react-css-transition-replace/blob/master/UPGRADE_GUIDE.md).

However, the primary reason for the major version change is that this is a complete rewrite of the library and there were some instances in the past where consecutive animations were blocked due to a bug which should be fixed now. So although the API is practically the same I would just urge you to test the animations you have implemented again to ensure they all still work as expected.

If you encounter any issues let me know.

**Comment by FezVrasta** [comment]
uh I didn't notice that file, thanks!
