### ISSUE TITLE
Some elements enter suddenly, but leave properly

### ISSUE THREAD

**Issue by jlev** [marnusw/react-css-transition-replace#57]
I'm using react-css-transition-replace with a translate transition to slide across the page. Some children appear abruptly without sliding in, but will slide out nicely. The specific elements causing the problem are created with [react-rangeslider](https://github.com/whoisandy/react-rangeslider). I suspect it's something to do with the resize observer, which that library uses to detect size changes on the created elements.

Are there known issues with the [resize observer polyfill](https://github.com/que-etc/resize-observer-polyfill) or window resize event listener and this transition library?

**Comment by marnusw** [comment]
It has never been used with resizing windows, so there are no known issues but that is not to say there won't be any. If the parent isn't sized right when the animation begins I can imagine that there could be some unexpected behaviour.

You might try using the `appear` animation to ensure that you are not missing out on animation when the component is mounted, in case that is the issue rather than parent size.

If this doesn't help and you can figure our what is happening and wouldn't mind submitting a PR if you find a solution I will very happily consider it.

**Comment by jlev** [comment]
Never mind, there was an issue with my transition CSS. Taking a walk fixed the problem.
Thanks for the really nice library.

**Comment by Richacinas** [comment]
@jlev 

I'm having exactly the same issue as you. Using react range slider inside the rendered components is causing elements to enter suddenly, but leave properly...

Could you please share your solution?

Thanks so much.

**Comment by Richacinas** [comment]
Got it. Regarding this react-rangeslider library...

If I go into it, and comment the line 249 that is inside componentDidMount, my transition doesn't break anymore.

```
value: function componentDidMount() {
      //this.handleUpdate();
      var resizeObserver = new _resizeObserverPolyfill2.default(this.handleUpdate);
      resizeObserver.observe(this.slider);
}
```

Basically, it means not calling handleUpdate, which is causing a setState as soon as the component is mounted. 

It works now, just don't know why... Might help for other cases of libraries where state is being set as soon as the component is mounted.

Cheers
