### ISSUE TITLE
React router redirection is bugged

### ISSUE THREAD

**Issue by smoleniuch** [marnusw/react-css-transition-replace#60]
I have stumbled on an issue with using this package with `react-router`.

When i use `<Redirect />` component from `react-router-dom` module inside the `<Switch />` component  which is rendered by transition i am getting a warning:

> You tried to redirect to the same route you're currently on: "/route"

I have make [sandbox](https://codesandbox.io/embed/vn4kq8njw3?fontsize=14) to reproduce this issue.To reproduce it click on the force redireciton link.

This is very annoying because when i am testing my application this makes infinitive loop of redirection.

Btw. Thanks for this module.

Cheers!

**Comment by marnusw** [comment]
I see. Thank you for creating the sandbox. No immediate thoughts spring to mind. I will look into it as soon as I can.

**Comment by fdev** [comment]
I have [forked the sandbox](https://codesandbox.io/s/7bcpg) example and, using the latest version of `react-router-dom` and a small refactor, could get rid of the error.

I believe the error was not caused by `react-css-transition-replace`, but caused by the `<Route render={location => ... } />` wrapper.

**Comment by marnusw** [comment]
Excellent! Thank you for taking the time @fdev. I'm glad switching to the router's hooks API fixes this.
